web:
  build: .
  volumes:
    - ".:/code"
  ports:
    - "80:80"
  links:
     - redis
     - db
db:
  image: postgres
  environment:
    POSTGRES_PASSWORD: docker
    POSTGRES_USER: docker

redis:
   image: redis
